### ISSUE TITLE
INSTALL.md Problem

### ISSUE THREAD

**Issue by ComeOnComeOnTurnYourRadioOn** [Scalsol/mega.pytorch#120]
Hello,
I failed to follow the mega.pytorch.INSTALL.md due to the CUDA version being incompatible with the Pytorch version. I exactly followed the INSTALL.md step by step, and I did install pytorch=1.3.0 and cudatoolkit=10.0 successfully. But, when I tried to install apex, some errors just popped up.
Below is the error message.

`
torch.__version__  = 1.3.0

Compiling cuda extensions with
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:08:53_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0
from /usr/local/cuda/bin

Traceback (most recent call last):
  File "setup.py", line 178, in <module>
    check_cuda_torch_binary_vs_bare_metal(CUDA_HOME)
  File "setup.py", line 37, in check_cuda_torch_binary_vs_bare_metal
    + "In some cases, a minor-version mismatch will not cause later errors:  "
RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.0.130.
In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
`

I followed this link and the answer is to comment this check. I also followed this answer, but another even weird error message was poped up.

`
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
Traceback (most recent call last):
  File "setup.py", line 788, in <module>
    extras_require=extras,
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 353, in build_extensions
    build_ext.build_extensions(self)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 554, in build_extension
    depends=ext.depends,
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/setuptools/_distutils/ccompiler.py", line 599, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 269, in unix_wrap_compile
    "'-fPIC'"] + cflags + _get_cuda_arch_flags(cflags)
  File "/home/wangpengfei/anaconda3/envs/MEGA/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 991, in _get_cuda_arch_flags
    raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
ValueError: Unknown CUDA arch (8.6) or GPU not supported
` 

BTW, the GPU I am currently using is 3090. I am not too sure if 3090 can support the CUDA version which is less than 11. The cuda drive I am installing is 455.45.01.

May I please ask you if there are any other ways to sort out my problems??

Thank you so much for your help. Looking forward to your response soon! 
Cheers! :-)

**Comment by lemyanh2612** [comment]
I can install this work on GTX1070  and GTX2080, but can not install them on GTX3090.

For apex, You can follow:

1. git clone https://github.com/NVIDIA/apex.git
2. cd apex
3. git checkout e3794f422628d453b036f69de476bf16a0a838ac
4. python setup.py install
