### ISSUE TITLE
关于您的论文复现

### ISSUE THREAD

**Issue by Smallwhite999** [Scalsol/mega.pytorch#41]
作者您好，我是按照 README.md 上面的配置的，训练和推理也是按照那个里面的命令执行的，但是还是报错，是除了按照 README.md 里面的配资之外还要按照哪个配置啊？劳烦解答一下，谢谢！

**Comment by Scalsol** [comment]
请讲下你的环境 (python版本, nvcc, gcc等), 然后讲一下是运行什么命令导致报错了, 谢谢!

**Comment by Smallwhite999** [comment]
我安装的时候都是按照下面这个安装的：   
      
训练的命令是按照这个操作的：
这些配置完成之后报错是这样的：
python -m torch.distributed.launch \
> --nproc_per_node=2 \
> tools/train_net.py \
> --master_port=$((RANDOM+10000)) \
> --config-file configs/MEGA/vid_R_101_c4_MEGA_1x.yaml \
> --motion-specific
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/wang/anaconda3/envs/cvbaseline/bin/python: can't open file 'tools/train_net.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/site-packages/torch/distributed/launch.py", line 258, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/****/anaconda3/envs/cvbaseline/bin/python', '-u', 'tools/train_net.py', '--local_rank=1', '--master_port=16269', '--config-file', 'configs/MEGA/vid_R_101_c4_MEGA_1x.yaml', '--motion-specific']' returned non-zero exit status 2.
/home/wang/anaconda3/envs/cvbaseline/bin/python: can't open file 'tools/train_net.py': [Errno 2] No such file or directory
并且我跳过这个命令“--motion-specific”的时候报错是这样的：
python -m torch.distributed.launch \
> --nproc_per_node=2 \
> tools/train_net.py \
> --master_port=$((RANDOM + 10000)) \
> --config-file configs/MEGA/vid_R_101_C4_MEGA_1x.yaml \
> OUTPUT_DIR training_dir/MEGA_R_101_1x
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/wang/anaconda3/envs/cvbaseline/bin/python: can't open file 'tools/train_net.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
/home/wang/anaconda3/envs/cvbaseline/bin/python: can't open file 'tools/train_net.py': [Errno 2] No such file or directory
  File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/site-packages/torch/distributed/launch.py", line 258, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/wangdicong19b/anaconda3/envs/cvbaseline/bin/python', '-u', 'tools/train_net.py', '--local_rank=1', '--master_port=37600', '--config-file', 'configs/MEGA/vid_R_101_C4_MEGA_1x.yaml', 'OUTPUT_DIR', 'training_dir/MEGA_R_101_1x']' returned non-zero exit status 2.




在2020年7月23日 17:21，Yihong Chen<notifications@github.com> 写道：

请讲下你的环境 (python版本, nvcc, gcc等), 然后讲一下是运行什么命令导致报错了, 谢谢!

**Comment by Scalsol** [comment]
你运行命令的时候切换到`mega.pytorch`这个目录下了吗?

**Comment by Smallwhite999** [comment]
我再试一下吧，谢谢您的解答！
在2020年7月24日 10:33，Yihong Chen<notifications@github.com> 写道：

你运行命令的时候切换到mega.pytorch这个目录下了吗?

**Comment by launchauto** [comment]
> 我再试一下吧，谢谢您的解答！ 在2020年7月24日 10:33，Yihong Chen<notifications@github.com> 写道： 你运行命令的时候切换到mega.pytorch这个目录下了吗? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问你复现成功了么

**Comment by Smallwhite999** [comment]
并没有
在2020年8月26日 17:20，LauncH<notifications@github.com> 写道：

我再试一下吧，谢谢您的解答！ 在2020年7月24日 10:33，Yihong Chennotifications@github.com 写道： 你运行命令的时候切换到mega.pytorch这个目录下了吗? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问你复现成功了么

**Comment by fakechen** [comment]
> 并没有 在2020年8月26日 17:20，LauncH<notifications@github.com> 写道： 我再试一下吧，谢谢您的解答！ 在2020年7月24日 10:33，Yihong Chennotifications@github.com 写道： 你运行命令的时候切换到mega.pytorch这个目录下了吗? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 请问你复现成功了么 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问复现成功了吗

**Comment by fakechen** [comment]
在collate_batch.py中
transposed_batch[0][0]的数据结构tensor
为什么用字典操作啊

**Comment by Jezzzzz** [comment]
> 我安装的时候都是按照下面这个安装的： 训练的命令是按照这个操作的： 这些配置完成之后报错是这样的： python -m torch.distributed.launch \
> --nproc_per_node=2 \ tools/train_net.py \ --master_port=$((RANDOM+10000)) \ --config-file configs/MEGA/vid_R_101_c4_MEGA_1x.yaml \ --motion-specific
> ***************************************** Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. ***************************************** /home/wang/anaconda3/envs/cvbaseline/bin/python: can't open file 'tools/train_net.py': [Errno 2] No such file or directory Traceback (most recent call last): File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/site-packages/torch/distributed/launch.py", line 263, in <module> main() File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/site-packages/torch/distributed/launch.py", line 258, in main raise subprocess.CalledProcessError(returncode=process.returncode, subprocess.CalledProcessError: Command '['/home/****/anaconda3/envs/cvbaseline/bin/python', '-u', 'tools/train_net.py', '--local_rank=1', '--master_port=16269', '--config-file', 'configs/MEGA/vid_R_101_c4_MEGA_1x.yaml', '--motion-specific']' returned non-zero exit status 2. /home/wang/anaconda3/envs/cvbaseline/bin/python: can't open file 'tools/train_net.py': [Errno 2] No such file or directory 并且我跳过这个命令“--motion-specific”的时候报错是这样的： python -m torch.distributed.launch \
> --nproc_per_node=2 \ tools/train_net.py \ --master_port=$((RANDOM + 10000)) \ --config-file configs/MEGA/vid_R_101_C4_MEGA_1x.yaml \ OUTPUT_DIR training_dir/MEGA_R_101_1x
> ***************************************** Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. ***************************************** /home/wang/anaconda3/envs/cvbaseline/bin/python: can't open file 'tools/train_net.py': [Errno 2] No such file or directory Traceback (most recent call last): File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, /home/wang/anaconda3/envs/cvbaseline/bin/python: can't open file 'tools/train_net.py': [Errno 2] No such file or directory File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/site-packages/torch/distributed/launch.py", line 263, in <module> main() File "/home/wang/anaconda3/envs/cvbaseline/lib/python3.8/site-packages/torch/distributed/launch.py", line 258, in main raise subprocess.CalledProcessError(returncode=process.returncode, subprocess.CalledProcessError: Command '['/home/wangdicong19b/anaconda3/envs/cvbaseline/bin/python', '-u', 'tools/train_net.py', '--local_rank=1', '--master_port=37600', '--config-file', 'configs/MEGA/vid_R_101_C4_MEGA_1x.yaml', 'OUTPUT_DIR', 'training_dir/MEGA_R_101_1x']' returned non-zero exit status 2. 在2020年7月23日 17:21，Yihong Chen<notifications@github.com> 写道： 请讲下你的环境 (python版本, nvcc, gcc等), 然后讲一下是运行什么命令导致报错了, 谢谢! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我也遇到了相同的问题。请问，您解决了吗？

**Comment by joe660** [comment]
> > 并没有 在2020年8月26日 17:20，LauncH[notifications@github.com](mailto:notifications@github.com) 写道： 我再试一下吧，谢谢您的解答！ 在2020年7月24日 10:33，Yihong [Chennotifications@github.com](mailto:Chennotifications@github.com) 写道： 你运行命令的时候切换到mega.pytorch这个目录下了吗? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 请问你复现成功了么 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 请问复现成功了吗

复现MEGA中  我遇到了同样的问题  请问您解决这个问题了吗？麻烦你了  谢谢！

**Comment by joe660** [comment]
> 我也遇到了相同的问题。请问，您解决了吗？
复现MEGA中  我遇到了同样的问题  请问您解决这个问题了吗？麻烦你了  谢谢！

**Comment by fakechen** [comment]
还是没有解决23333333333333------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月8日(星期四) 晚上6:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Scalsol/mega.pytorch] 关于您的论文复现 (#41)

**Comment by joe660** [comment]
> 还是没有解决23333333333333------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年4月8日(星期四) 晚上6:18 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Scalsol/mega.pytorch] 关于您的论文复现 (#41)

时间过去了快半年了   你现在不做视频检测这一块了吗？

**Comment by joe660** [comment]
你的python版本是作者推荐的3.7还是其他版本，我使用的是3.7.  出现了这个问题。

**Comment by fakechen** [comment]
换了个轮子已经做完啦。。。建议你别再费力气了。应该有一些问题------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月8日(星期四) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Scalsol/mega.pytorch] 关于您的论文复现 (#41)

**Comment by fakechen** [comment]
是3.7------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月8日(星期四) 晚上9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Scalsol/mega.pytorch] 关于您的论文复现 (#41)

**Comment by joe660** [comment]
可是为什么有的人复现成功了呢？头大。。。。
 
你之后换了其他模型，可以方便给个链接吗？谢谢！

**Comment by fakechen** [comment]
其实完全按照作者配置，也会出现问题，我已经放弃啦。 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月8日(星期四) 晚上9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Scalsol/mega.pytorch] 关于您的论文复现 (#41)

**Comment by joe660** [comment]
那你之后使用什么模型进行训练，可以分享下吗？pytroch版本？

**Comment by fakechen** [comment]
是师兄的一个框架，你懂的。我已经毕业了，不太记得清了，抱歉应该帮不了你了。 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月8日(星期四) 晚上9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Scalsol/mega.pytorch] 关于您的论文复现 (#41)

**Comment by joe660** [comment]
> 是师兄的一个框架，你懂的。我已经毕业了，不太记得清了，抱歉应该帮不了你了。 ------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年4月8日(星期四) 晚上9:14 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Scalsol/mega.pytorch] 关于您的论文复现 (#41)

行吧 难受，，，，，，
