### ISSUE TITLE
The results of RDN

### ISSUE THREAD

**Issue by xc-csc101** [Scalsol/mega.pytorch#55]
Thanks for your impressive codebase. I try to reproduce the results of RDN, but the best result is 80.9 which is lower than 81.7 obviously. Shoud I modify any parameters or add any training tricks?

**Comment by ZhijunHou** [comment]
Hi, I just got 78.%. Have you modified any parameters setting?

**Comment by xc-csc101** [comment]
> Hi, I just got 78.%. Have you modified any parameters setting?

No, I just use default settings. According to my experimental results, the map is different every time because of random sampling, the avearge map I got is about 80.6

**Comment by ZhijunHou** [comment]
Thanks!

**Comment by zhanghaoo** [comment]
为什么你们都可以跑通啊！啊啊啊啊啊啊啊啊！

我的为什么出来start training就不动了呢？

**Comment by joe660** [comment]
> Thanks for your impressive codebase. I try to reproduce the results of RDN, but the best result is 80.9 which is lower than 81.7 obviously. Shoud I modify any parameters or add any training tricks?
你好 请问你复现MEGA的时候是按照作者提供的不步骤进行的吗？求回复 谢谢！！

**Comment by joe660** [comment]
> Thanks for your impressive codebase. I try to reproduce the results of RDN, but the best result is 80.9 which is lower than 81.7 obviously. Shoud I modify any parameters or add any training tricks?

我使用原始的Faster RCNN可以运行成功并得到MAP指标，但是使用FGFA和MEGA等只能训练，训练完后测试就报错，错误如下：

2021-04-10 16:08:44,319 mega_core.utils.checkpoint INFO: Saving checkpoint to /home/zhangzp/mega.pytorch-master/demo/R_101_1/model_final.pth
2021-04-10 16:08:46,303 mega_core.trainer INFO: Total training time: 0:01:17.140829 (0.7714 s / it)
Traceback (most recent call last):
File "tools/train_net.py", line 226, in
main()
File "tools/train_net.py", line 222, in main
run_test(cfg, model, args.distributed, args.motion_specific)
File "tools/train_net.py", line 123, in run_test
data_loaders_val = make_data_loader(cfg, is_train=False, is_distributed=distributed)
File "/home/zhangzp/mega.pytorch-master/mega_core/data/build.py", line 167, in make_data_loader
datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train or is_for_period, cfg.MODEL.VID.METHOD)
File "/home/zhangzp/mega.pytorch-master/mega_core/data/build.py", line 47, in build_dataset
dataset = factory(**args)
File "/home/zhangzp/mega.pytorch-master/mega_core/data/datasets/vid_mega.py", line 10, in init
super(VIDMEGADataset, self).init(image_set, data_dir, img_dir, anno_path, img_index, transforms, is_train=is_train)
File "/home/zhangzp/mega.pytorch-master/mega_core/data/datasets/vid.py", line 48, in init
self.image_set_index = ["%s/%06d" % (x[0], int(x[2])) for x in lines]
File "/home/zhangzp/mega.pytorch-master/mega_core/data/datasets/vid.py", line 48, in
self.image_set_index = ["%s/%06d" % (x[0], int(x[2])) for x in lines]
IndexError: list index out of range
Traceback (most recent call last):
File "/home/zhangzp/miniconda2/envs/MEGA/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/home/zhangzp/miniconda2/envs/MEGA/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/zhangzp/miniconda2/envs/MEGA/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in
main()
File "/home/zhangzp/miniconda2/envs/MEGA/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zhangzp/miniconda2/envs/MEGA/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--master_port=19650', '--config-file', 'configs/MEGA/vid_R_101_C4_MEGA_1x.yaml', '--motion-specific', 'OUTPUT_DIR', '/home/zhangzp/mega.pytorch-master/demo/R_101_1']' returned non-zero exit status 1.

麻烦您可以抽空给些建议 谢谢啊

**Comment by joe660** [comment]
> Thanks for your impressive codebase. I try to reproduce the results of RDN, but the best result is 80.9 which is lower than 81.7 obviously. Shoud I modify any parameters or add any training tricks?

大哥还在吗  ？你知道VID_val_frames.txt和VID_val_videos.txt两个txt文件，在验证的时候应该使用那个呢？？？？求回复

麻烦您可以抽空给些建议 谢谢啊

**Comment by b762927** [comment]
Hello, I want to ask the RDN how to train in two-stage， I find the network first-stage training code is the same the second。
