### ISSUE TITLE
  属性错误  nms = amp.float_function(_C.nms)    AttributeError(name) AttributeError: nms

### ISSUE THREAD

**Issue by Zhangming001** [Scalsol/mega.pytorch#61]
/home/ming/anaconda3/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
Traceback (most recent call last):
  File "demo_1.py", line 7, in <module>
    from demo.predictor import VIDDemo
  File "../demo/predictor.py", line 11, in <module>
    from mega_core.modeling.detector import build_detection_model
  File "../mega_core/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "../mega_core/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "../mega_core/modeling/detector/generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "../mega_core/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "../mega_core/modeling/backbone/backbone.py", line 7, in <module>
    from mega_core.modeling.make_layers import conv_with_kaiming_uniform
  File "../mega_core/modeling/make_layers.py", line 10, in <module>
    from mega_core.layers import Conv2d
  File "../mega_core/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "../mega_core/layers/nms.py", line 8, in <module>
    nms = amp.float_function(_C.nms)
  File "/home/ming/anaconda3/lib/python3.8/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: nms
请问这个问题该怎么解决

**Comment by wyz-gitt** [comment]
Hello,Hi, have you solved this problem?
