### ISSUE TITLE
There is a question when using the demo.py to inference my own video

### ISSUE THREAD

**Issue by tianlanshidai** [Scalsol/mega.pytorch#68]
There is a question when using the demo.py to inference my own video:
I have use the script that in  your readme:

python demo/demo.py base configs/vid_R_101_C4_1x.yaml models/R_101.pth --video       --visualize-path datasets/test.mp4          --output-folder visualization --output-video

However,there is a error:
Segmentation fault (core dumped),

Have you meet this problem?Can you help me to deal with it?Thank you very much.

**Comment by khadijakhaldi** [comment]
I'm having the same error

**Comment by joe660** [comment]
> I'm having the same error

I can run successfully and get map index by using the original fast RCNN, but only FGFa and mega can be trained. After training, the test will report errors. The error is as follows:

2021-04-10 16:08:44,319 mega_core.utils.checkpoint INFO: Saving checkpoint to /home/zhangzp/mega.pytorch-master/demo/R_101_1/model_final.pth
2021-04-10 16:08:46,303 mega_core.trainer INFO: Total training time: 0:01:17.140829 (0.7714 s / it)
Traceback (most recent call last):
File "tools/train_net.py", line 226, in
main()
File "tools/train_net.py", line 222, in main
run_test(cfg, model, args.distributed, args.motion_specific)
File "tools/train_net.py", line 123, in run_test
data_loaders_val = make_data_loader(cfg, is_train=False, is_distributed=distributed)
File "/home/zhangzp/mega.pytorch-master/mega_core/data/build.py", line 167, in make_data_loader
datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train or is_for_period, cfg.MODEL.VID.METHOD)
File "/home/zhangzp/mega.pytorch-master/mega_core/data/build.py", line 47, in build_dataset
dataset = factory(**args)
File "/home/zhangzp/mega.pytorch-master/mega_core/data/datasets/vid_mega.py", line 10, in init
super(VIDMEGADataset, self).init(image_set, data_dir, img_dir, anno_path, img_index, transforms, is_train=is_train)
File "/home/zhangzp/mega.pytorch-master/mega_core/data/datasets/vid.py", line 48, in init
self.image_set_index = ["%s/%06d" % (x[0], int(x[2])) for x in lines]
File "/home/zhangzp/mega.pytorch-master/mega_core/data/datasets/vid.py", line 48, in
self.image_set_index = ["%s/%06d" % (x[0], int(x[2])) for x in lines]
IndexError: list index out of range
Traceback (most recent call last):
File "/home/zhangzp/miniconda2/envs/MEGA/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/home/zhangzp/miniconda2/envs/MEGA/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/zhangzp/miniconda2/envs/MEGA/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in
main()
File "/home/zhangzp/miniconda2/envs/MEGA/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zhangzp/miniconda2/envs/MEGA/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--master_port=19650', '--config-file', 'configs/MEGA/vid_R_101_C4_MEGA_1x.yaml', '--motion-specific', 'OUTPUT_DIR', '/home/zhangzp/mega.pytorch-master/demo/R_101_1']' returned non-zero exit status 1.

Thank you for your time

**Comment by guermal** [comment]
Did you solve the issue ?
