### ISSUE TITLE
关于其中的FGFA，很可能有错误，请看下面

### ISSUE THREAD

**Issue by fengyue20** [Scalsol/mega.pytorch#77]
看了您code中FGFA中的部分，发现了一个问题，在测试的时候，您的代码没有导入flownet的预训练模型，经过我试验得到的结果就是，对于一个相同的图像序列，我用您的demo中的FGFA方法进行检测，什么都不改变，检测两遍会得到不同的结果，结果差别比较大，但是在demo中加入checkpointer.load_flownet(),进行多遍检测，结果是一样的，希望您和使用者周知。

**Comment by xiaoxiaopeng1998** [comment]
@fengyue20 
大神，你是在Windows还是Ubuntu上跑成功的？
可否指导一下。。

**Comment by joe660** [comment]
> 看了您code中FGFA中的部分，发现了一个问题，在测试的时候，您的代码没有导入flownet的预训练模型，经过我试验得到的结果就是，对于一个相同的图像序列，我用您的demo中的FGFA方法进行检测，什么都不改变，检测两遍会得到不同的结果，结果差别比较大，但是在demo中加入checkpointer.load_flownet(),进行多遍检测，结果是一样的，希望您和使用者周知。

我使用原始的Faster RCNN可以运行成功并得到MAP指标，但是使用FGFA和MEGA只能训练，训练完后测试就报错，错误如下：

2021-04-10 16:08:44,319 mega_core.utils.checkpoint INFO: Saving checkpoint to /home/zhangzp/mega.pytorch-master/demo/R_101_1/model_final.pth
2021-04-10 16:08:46,303 mega_core.trainer INFO: Total training time: 0:01:17.140829 (0.7714 s / it)
Traceback (most recent call last):
  File "tools/train_net.py", line 226, in <module>
    main()
  File "tools/train_net.py", line 222, in main
    run_test(cfg, model, args.distributed, args.motion_specific)
  File "tools/train_net.py", line 123, in run_test
    data_loaders_val = make_data_loader(cfg, is_train=False, is_distributed=distributed)
  File "/home/zhangzp/mega.pytorch-master/mega_core/data/build.py", line 167, in make_data_loader
    datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train or is_for_period, cfg.MODEL.VID.METHOD)
  File "/home/zhangzp/mega.pytorch-master/mega_core/data/build.py", line 47, in build_dataset
    dataset = factory(**args)
  File "/home/zhangzp/mega.pytorch-master/mega_core/data/datasets/vid_mega.py", line 10, in __init__
    super(VIDMEGADataset, self).__init__(image_set, data_dir, img_dir, anno_path, img_index, transforms, is_train=is_train)
  File "/home/zhangzp/mega.pytorch-master/mega_core/data/datasets/vid.py", line 48, in __init__
    self.image_set_index = ["%s/%06d" % (x[0], int(x[2])) for x in lines]
  File "/home/zhangzp/mega.pytorch-master/mega_core/data/datasets/vid.py", line 48, in <listcomp>
    self.image_set_index = ["%s/%06d" % (x[0], int(x[2])) for x in lines]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/zhangzp/miniconda2/envs/MEGA/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhangzp/miniconda2/envs/MEGA/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhangzp/miniconda2/envs/MEGA/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/zhangzp/miniconda2/envs/MEGA/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zhangzp/miniconda2/envs/MEGA/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--master_port=19650', '--config-file', 'configs/MEGA/vid_R_101_C4_MEGA_1x.yaml', '--motion-specific', 'OUTPUT_DIR', '/home/zhangzp/mega.pytorch-master/demo/R_101_1']' returned non-zero exit status 1.

麻烦您可以抽空给些建议  谢谢啊

**Comment by joe660** [comment]
> 看了您code中FGFA中的部分，发现了一个问题，在测试的时候，您的代码没有导入flownet的预训练模型，经过我试验得到的结果就是，对于一个相同的图像序列，我用您的demo中的FGFA方法进行检测，什么都不改变，检测两遍会得到不同的结果，结果差别比较大，但是在demo中加入checkpointer.load_flownet(),进行多遍检测，结果是一样的，希望您和使用者周知。



> @fengyue20
> 大神，你是在Windows还是Ubuntu上跑成功的？
> 可否指导一下。。

你知道加到哪里吗？ 我在使用FGFA测试的时候效果极差，不知道是不是因为这？

**Comment by joe660** [comment]
> 看了您code中FGFA中的部分，发现了一个问题，在测试的时候，您的代码没有导入flownet的预训练模型，经过我试验得到的结果就是，对于一个相同的图像序列，我用您的demo中的FGFA方法进行检测，什么都不改变，检测两遍会得到不同的结果，结果差别比较大，但是在demo中加入checkpointer.load_flownet(),进行多遍检测，结果是一样的，希望您和使用者周知。

可以加个好友吗？  我按照你说的添加了   还可以    我使用自己的数据集训练，AP从大到小一次是FGFA>MEGA>Fasterrcnn。但是在demo显示的时候  FGFA显示相比MEGA和Faster还是很差，这是什么原因呢？   光流还需要重新训练？？？

**Comment by liubinbinbin** [comment]
使用DFF的时候也出现了这个问题，怎么添加这句代码呢

**Comment by liubinbinbin** [comment]
解决了，这是在使用demo的时候，如果你要使用光流相关的代码，一要记得在load model的时候，传入参数时加入flownet=None

**Comment by meikorol** [comment]
> 

请问可以加个好友指导一下怎么跑通这个代码吗，不胜感激！

**Comment by liubinbinbin** [comment]
> 我都搞忘了，我用的30系列的卡，配置的时候很难，要改一些低层的代码，如果你用20系列的估计会好配一些
